generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Inquiry
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          inquiry
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: お問い合わせ一覧
      filter:  ~
      form:    ~
      edit:
        title: お問い合わせ詳細
      new:     ~
      confirm: ~
