generator:
  class: sfDoctrineGenerator
  param:
    model_class:           LinkBanner
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          link_banner
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        pic:     {label: 画像}
        name:    {label: テキスト}
        url:     {label: URL}
        comment: {label: コメント}
      list:
        title: リンクバナー一覧
        display: [id, _pic, name, url, comment]
      filter:  ~
      form:    ~
      edit:
        title: リンクバナー編集
      new:
        title: 新規リンクバナー追加
      confirm: ~
