generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Rank
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          rank
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        id:   {label: No.}
        name: {label: タイトル}
        pic:  {label: 画像}
      list:
        title: コンパニオンランク一覧
        display: [id, name, _pic]
      filter:  ~
      form:    ~
      edit:
        title: コンパニオンランク編集
      new:
        title: コンパニオンランク新規追加
      confirm: ~
